/* The following code was generated by JFlex 1.5.1 */


/* --------------------------Codigo de Usuario----------------------- */
package gramatica;

import java_cup.runtime.*;
import java.io.Reader;
      

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.1
 * from the specification file <tt>alexico.flex</tt>
 */
class AnalizadorLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\23\6\0"+
    "\1\14\1\15\1\12\1\10\1\0\1\11\1\0\1\13\1\4\11\5"+
    "\2\0\1\20\1\22\1\21\2\0\32\7\4\0\1\6\1\0\1\31"+
    "\1\7\1\41\1\43\1\27\1\30\1\40\1\37\1\34\2\7\1\32"+
    "\1\42\1\35\1\36\1\50\1\46\1\25\1\33\1\24\1\26\1\44"+
    "\4\7\1\16\1\7\1\17\157\0\1\47\3\0\1\45\uff0e\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\2\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\2\1\12\5\1\1\2\5\1\20\1\21\1\22\1\23"+
    "\5\5\1\24\6\5\1\0\13\5\1\0\3\5\1\0"+
    "\2\5\1\25\4\5\1\26\1\27\2\5\1\0\3\5"+
    "\1\0\2\5\1\30\1\5\1\31\2\5\1\32\1\0"+
    "\1\5\1\33\1\5\1\0\3\5\1\34\1\5\1\0"+
    "\2\5\1\35\1\36\3\5\1\37\3\5\1\40\1\41"+
    "\1\42\1\43\30\5";

  private static int [] zzUnpackAction() {
    int [] result = new int[140];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\51\0\122\0\51\0\51\0\51\0\173\0\244"+
    "\0\51\0\51\0\51\0\51\0\51\0\51\0\51\0\51"+
    "\0\315\0\366\0\u011f\0\u0148\0\u0171\0\u019a\0\u01c3\0\u01ec"+
    "\0\u0215\0\u023e\0\u0267\0\u0290\0\u02b9\0\u02e2\0\u030b\0\u0334"+
    "\0\u035d\0\51\0\51\0\51\0\51\0\u0386\0\u03af\0\u03d8"+
    "\0\u0401\0\u042a\0\u0453\0\u047c\0\u04a5\0\u04ce\0\u04f7\0\u0520"+
    "\0\u0549\0\u0572\0\u059b\0\u05c4\0\u05ed\0\u0616\0\u063f\0\u0668"+
    "\0\u0691\0\u06ba\0\u06e3\0\u070c\0\u0735\0\u075e\0\u0787\0\u07b0"+
    "\0\u07d9\0\u0802\0\u082b\0\u0854\0\u0854\0\u087d\0\u08a6\0\u08cf"+
    "\0\u08f8\0\u0854\0\u0854\0\u0921\0\u094a\0\u0973\0\u099c\0\u09c5"+
    "\0\u09ee\0\u0a17\0\u0a40\0\u0a69\0\u0a69\0\u0a92\0\u0a69\0\u0abb"+
    "\0\u0ae4\0\u0a69\0\u0b0d\0\u0b36\0\u0a69\0\u0b5f\0\u0b88\0\u0bb1"+
    "\0\u0bda\0\u0c03\0\u0bda\0\u0c2c\0\u0c55\0\u0c7e\0\u0ca7\0\51"+
    "\0\u0bda\0\u0cd0\0\u0cf9\0\u0d22\0\51\0\u0d4b\0\u0d74\0\u0d9d"+
    "\0\u0d9d\0\u0d9d\0\u0d9d\0\u0d9d\0\u0dc6\0\u0def\0\u0e18\0\u0e41"+
    "\0\u0e6a\0\u0e93\0\u0ebc\0\u0ee5\0\u0f0e\0\u0f37\0\u0f60\0\u0f89"+
    "\0\u0fb2\0\u0fdb\0\u1004\0\u102d\0\u1056\0\u107f\0\u10a8\0\u10d1"+
    "\0\u10fa\0\u1123\0\u114c\0\51";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[140];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\2\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\10\1\27\1\30"+
    "\1\31\1\10\1\32\3\10\1\33\1\10\1\34\1\35"+
    "\1\36\1\10\1\2\1\10\1\37\1\40\53\0\1\4"+
    "\52\0\2\7\47\0\2\41\1\0\1\41\14\0\21\41"+
    "\1\0\1\41\1\0\1\41\22\0\1\42\50\0\1\43"+
    "\50\0\1\44\50\0\1\45\32\0\2\41\1\0\1\41"+
    "\14\0\1\41\1\46\17\41\1\0\1\41\1\0\1\41"+
    "\4\0\2\41\1\0\1\41\14\0\3\41\1\47\15\41"+
    "\1\0\1\41\1\0\1\41\4\0\2\41\1\0\1\41"+
    "\14\0\11\41\1\50\7\41\1\0\1\41\1\0\1\41"+
    "\4\0\2\41\1\0\1\41\14\0\5\41\1\51\13\41"+
    "\1\0\1\41\1\0\1\41\4\0\2\41\1\0\1\41"+
    "\14\0\11\41\1\52\7\41\1\0\1\41\1\0\1\41"+
    "\4\0\2\41\1\0\1\41\14\0\10\41\1\53\10\41"+
    "\1\0\1\41\1\0\1\41\4\0\2\41\1\0\1\41"+
    "\14\0\5\41\1\54\13\41\1\0\1\41\1\0\1\41"+
    "\4\0\2\41\1\0\1\41\14\0\10\41\1\55\10\41"+
    "\1\0\1\41\1\0\1\41\4\0\2\41\1\0\1\41"+
    "\14\0\3\41\1\56\4\41\1\57\1\41\1\60\6\41"+
    "\1\0\1\41\1\0\1\41\4\0\2\41\1\0\1\41"+
    "\14\0\3\41\1\61\15\41\1\0\1\41\1\0\1\41"+
    "\35\0\1\62\17\0\2\41\1\0\1\41\14\0\2\41"+
    "\1\63\16\41\1\0\1\41\1\0\1\41\4\0\2\64"+
    "\1\0\1\64\14\0\21\64\1\0\1\64\1\0\1\64"+
    "\4\0\2\64\1\0\1\64\14\0\2\64\1\65\16\64"+
    "\1\0\1\64\1\0\1\64\4\0\2\64\1\0\1\64"+
    "\14\0\15\64\1\66\3\64\1\0\1\64\1\0\1\64"+
    "\4\0\2\64\1\0\1\64\14\0\1\67\20\64\1\0"+
    "\1\64\1\0\1\64\4\0\2\64\1\0\1\64\14\0"+
    "\6\64\1\70\12\64\1\0\1\64\1\0\1\64\4\0"+
    "\2\64\1\0\1\64\14\0\2\64\1\71\16\64\1\0"+
    "\1\64\1\0\1\64\4\0\2\64\1\0\1\64\14\0"+
    "\11\64\1\72\7\64\1\0\1\64\1\0\1\64\4\0"+
    "\2\64\1\0\1\64\14\0\14\64\1\73\4\64\1\0"+
    "\1\64\1\0\1\64\4\0\2\64\1\0\1\64\14\0"+
    "\1\64\1\74\17\64\1\0\1\64\1\0\1\64\4\0"+
    "\2\64\1\0\1\64\14\0\17\64\1\75\1\64\1\76"+
    "\1\64\1\0\1\64\4\0\2\64\1\0\1\64\14\0"+
    "\3\64\1\77\15\64\1\0\1\64\1\0\1\64\4\0"+
    "\2\64\1\0\1\64\14\0\20\64\1\100\1\0\1\64"+
    "\1\0\1\64\4\0\2\64\1\0\1\64\14\0\15\64"+
    "\1\101\3\64\1\0\1\64\1\0\1\64\43\0\1\102"+
    "\11\0\2\64\1\0\1\64\14\0\6\64\1\103\12\64"+
    "\1\0\1\64\1\0\1\64\4\0\2\104\1\0\1\104"+
    "\14\0\21\104\1\0\1\104\1\0\1\104\4\0\2\104"+
    "\1\0\1\104\14\0\3\104\1\105\15\104\1\0\1\104"+
    "\1\0\1\104\4\0\2\104\1\0\1\104\14\0\1\106"+
    "\20\104\1\0\1\104\1\0\1\104\4\0\2\104\1\0"+
    "\1\104\14\0\12\104\1\107\6\104\1\0\1\104\1\0"+
    "\1\104\4\0\2\104\1\0\1\104\14\0\7\104\1\110"+
    "\11\104\1\0\1\104\1\0\1\104\4\0\2\104\1\0"+
    "\1\104\14\0\6\104\1\111\12\104\1\0\1\104\1\0"+
    "\1\104\4\0\2\104\1\0\1\104\14\0\12\104\1\112"+
    "\6\104\1\0\1\104\1\0\1\104\4\0\2\104\1\0"+
    "\1\104\14\0\5\104\1\113\13\104\1\0\1\104\1\0"+
    "\1\104\4\0\2\104\1\0\1\104\14\0\15\104\1\114"+
    "\3\104\1\0\1\104\1\0\1\104\4\0\2\104\1\0"+
    "\1\104\14\0\10\104\1\115\10\104\1\0\1\104\1\0"+
    "\1\104\34\0\1\116\20\0\2\104\1\0\1\104\14\0"+
    "\11\104\1\117\7\104\1\0\1\104\1\0\1\104\4\0"+
    "\2\104\1\0\1\104\14\0\3\104\1\120\15\104\1\0"+
    "\1\104\1\0\1\104\4\0\2\104\1\0\1\104\14\0"+
    "\6\104\1\121\12\104\1\0\1\104\1\0\1\104\34\0"+
    "\1\122\20\0\2\104\1\0\1\104\14\0\14\104\1\123"+
    "\4\104\1\0\1\104\1\0\1\104\4\0\2\124\1\0"+
    "\1\124\14\0\21\124\1\0\1\124\1\0\1\124\4\0"+
    "\2\124\1\0\1\124\14\0\12\124\1\125\6\124\1\0"+
    "\1\124\1\0\1\124\4\0\2\124\1\0\1\124\14\0"+
    "\11\124\1\126\7\124\1\0\1\124\1\0\1\124\4\0"+
    "\2\124\1\0\1\124\14\0\3\124\1\127\15\124\1\0"+
    "\1\124\1\0\1\124\4\0\2\124\1\0\1\124\14\0"+
    "\5\124\1\130\13\124\1\0\1\124\1\0\1\124\4\0"+
    "\2\124\1\0\1\124\14\0\2\124\1\131\16\124\1\0"+
    "\1\124\1\0\1\124\4\0\2\124\1\0\1\124\14\0"+
    "\12\124\1\132\6\124\1\0\1\124\1\0\1\124\46\0"+
    "\1\133\6\0\2\124\1\0\1\124\14\0\1\134\20\124"+
    "\1\0\1\124\1\0\1\124\4\0\2\124\1\0\1\124"+
    "\14\0\1\124\1\135\17\124\1\0\1\124\1\0\1\124"+
    "\4\0\2\124\1\0\1\124\14\0\5\124\1\136\13\124"+
    "\1\0\1\124\1\0\1\124\41\0\1\137\13\0\2\124"+
    "\1\0\1\124\14\0\5\124\1\140\13\124\1\0\1\124"+
    "\1\0\1\124\4\0\2\141\1\0\1\141\14\0\21\141"+
    "\1\0\1\141\1\0\1\141\4\0\2\141\1\0\1\141"+
    "\14\0\15\141\1\142\3\141\1\0\1\141\1\0\1\141"+
    "\4\0\2\141\1\0\1\141\14\0\1\141\1\143\17\141"+
    "\1\0\1\141\1\0\1\141\4\0\2\141\1\0\1\141"+
    "\14\0\6\141\1\144\12\141\1\0\1\141\1\0\1\141"+
    "\26\0\1\145\26\0\2\141\1\0\1\141\14\0\1\141"+
    "\1\146\17\141\1\0\1\141\1\0\1\141\4\0\2\141"+
    "\1\0\1\141\14\0\1\141\1\147\17\141\1\0\1\141"+
    "\1\0\1\141\27\0\1\150\25\0\2\141\1\0\1\141"+
    "\14\0\1\141\1\151\17\141\1\0\1\141\1\0\1\141"+
    "\4\0\2\152\1\0\1\152\14\0\21\152\1\0\1\152"+
    "\1\0\1\152\4\0\2\152\1\0\1\152\14\0\3\152"+
    "\1\153\15\152\1\0\1\152\1\0\1\152\4\0\2\152"+
    "\1\0\1\152\14\0\5\152\1\154\13\152\1\0\1\152"+
    "\1\0\1\152\27\0\1\155\25\0\2\152\1\0\1\152"+
    "\14\0\5\152\1\156\13\152\1\0\1\152\1\0\1\152"+
    "\4\0\2\152\1\0\1\152\14\0\5\152\1\157\13\152"+
    "\1\0\1\152\1\0\1\152\4\0\2\160\1\0\1\160"+
    "\14\0\21\160\1\0\1\160\1\0\1\160\4\0\2\160"+
    "\1\0\1\160\14\0\7\160\1\161\11\160\1\0\1\160"+
    "\1\0\1\160\4\0\2\160\1\0\1\160\14\0\1\160"+
    "\1\162\17\160\1\0\1\160\1\0\1\160\4\0\2\160"+
    "\1\0\1\160\14\0\7\160\1\163\11\160\1\0\1\160"+
    "\1\0\1\160\4\0\2\160\1\0\1\160\14\0\1\160"+
    "\1\164\17\160\1\0\1\160\1\0\1\160\4\0\2\165"+
    "\1\0\1\165\14\0\21\165\1\0\1\165\1\0\1\165"+
    "\4\0\2\166\1\0\1\166\14\0\21\166\1\0\1\166"+
    "\1\0\1\166\4\0\2\167\1\0\1\167\14\0\21\167"+
    "\1\0\1\167\1\0\1\167\4\0\2\170\1\0\1\170"+
    "\14\0\21\170\1\0\1\170\1\0\1\170\4\0\2\171"+
    "\1\0\1\171\14\0\21\171\1\0\1\171\1\0\1\171"+
    "\4\0\2\172\1\0\1\172\14\0\21\172\1\0\1\172"+
    "\1\0\1\172\4\0\2\173\1\0\1\173\14\0\21\173"+
    "\1\0\1\173\1\0\1\173\4\0\2\174\1\0\1\174"+
    "\14\0\21\174\1\0\1\174\1\0\1\174\4\0\2\175"+
    "\1\0\1\175\14\0\21\175\1\0\1\175\1\0\1\175"+
    "\4\0\2\176\1\0\1\176\14\0\21\176\1\0\1\176"+
    "\1\0\1\176\4\0\2\177\1\0\1\177\14\0\21\177"+
    "\1\0\1\177\1\0\1\177\4\0\2\200\1\0\1\200"+
    "\14\0\21\200\1\0\1\200\1\0\1\200\4\0\2\201"+
    "\1\0\1\201\14\0\21\201\1\0\1\201\1\0\1\201"+
    "\4\0\2\202\1\0\1\202\14\0\21\202\1\0\1\202"+
    "\1\0\1\202\4\0\2\203\1\0\1\203\14\0\21\203"+
    "\1\0\1\203\1\0\1\203\4\0\2\204\1\0\1\204"+
    "\14\0\21\204\1\0\1\204\1\0\1\204\4\0\2\205"+
    "\1\0\1\205\14\0\21\205\1\0\1\205\1\0\1\205"+
    "\4\0\2\206\1\0\1\206\14\0\21\206\1\0\1\206"+
    "\1\0\1\206\4\0\2\207\1\0\1\207\14\0\21\207"+
    "\1\0\1\207\1\0\1\207\4\0\2\210\1\0\1\210"+
    "\14\0\21\210\1\0\1\210\1\0\1\210\4\0\2\211"+
    "\1\0\1\211\14\0\21\211\1\0\1\211\1\0\1\211"+
    "\4\0\2\212\1\0\1\212\14\0\21\212\1\0\1\212"+
    "\1\0\1\212\4\0\2\213\1\0\1\213\14\0\21\213"+
    "\1\0\1\213\1\0\1\213\4\0\2\214\1\0\1\214"+
    "\14\0\21\214\1\0\1\214\1\0\1\214";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4469];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\3\11\2\1\10\11\21\1\4\11"+
    "\14\1\1\0\13\1\1\0\3\1\1\0\13\1\1\0"+
    "\3\1\1\0\10\1\1\0\3\1\1\0\5\1\1\0"+
    "\2\1\1\11\4\1\1\11\36\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[140];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  AnalizadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  AnalizadorLexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader
             (in, java.nio.charset.Charset.forName("UTF-8")));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 118) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { throw new Error("Caracter ilegal <"+yytext()+">");
          }
        case 36: break;
        case 2: 
          { System.out.print(yytext());
                          return symbol(sym.NEWLINE);
          }
        case 37: break;
        case 3: 
          { /* ignora el espacio */
          }
        case 38: break;
        case 4: 
          { System.out.print(yytext()); 
                          return symbol(sym.NUM, new Integer(yytext()));
          }
        case 39: break;
        case 5: 
          { System.out.print(yytext());
                          return symbol(sym.ID, new String(yytext()));
          }
        case 40: break;
        case 6: 
          { System.out.print(" + ");
                          return symbol(sym.OP_SUMA);
          }
        case 41: break;
        case 7: 
          { System.out.print(" - ");
                          return symbol(sym.OP_RESTA);
          }
        case 42: break;
        case 8: 
          { System.out.print(" * ");
                          return symbol(sym.OP_MULT);
          }
        case 43: break;
        case 9: 
          { System.out.print(" * ");
                          return symbol(sym.OP_DIV);
          }
        case 44: break;
        case 10: 
          { System.out.print(" ( ");
                          return symbol(sym.PARENIZQ);
          }
        case 45: break;
        case 11: 
          { System.out.print(" ) ");
                          return symbol(sym.PARENDER);
          }
        case 46: break;
        case 12: 
          { System.out.print(" { ");
                          return symbol(sym.LLAVIZQ);
          }
        case 47: break;
        case 13: 
          { System.out.print(" } ");
                          return symbol(sym.LLAVDER);
          }
        case 48: break;
        case 14: 
          { System.out.print(" < ");
                          return symbol(sym.MENQUE, new String(yytext()));
          }
        case 49: break;
        case 15: 
          { System.out.print(" > ");
                          return symbol(sym.MAYQUE, new String(yytext()));
          }
        case 50: break;
        case 16: 
          { System.out.print(" <= ");
                          return symbol(sym.MENIGUAL, new String(yytext()));
          }
        case 51: break;
        case 17: 
          { System.out.print(" >= ");
                          return symbol(sym.MAYIGUAL, new String(yytext()));
          }
        case 52: break;
        case 18: 
          { System.out.print(" == ");
                          return symbol(sym.IGUAL, new String(yytext()));
          }
        case 53: break;
        case 19: 
          { System.out.print(" != ");
                          return symbol(sym.DISTINTO, new String(yytext()));
          }
        case 54: break;
        case 20: 
          { System.out.print(" si ");
                          return symbol(sym.SI, new String(yytext()));
          }
        case 55: break;
        case 21: 
          { System.out.print("true");
                          return symbol(sym.TRUE);
          }
        case 56: break;
        case 22: 
          { System.out.print(" sino ");
                          return symbol(sym.SINO, new String(yytext()));
          }
        case 57: break;
        case 23: 
          { System.out.print(" haga ");
                          return symbol(sym.HAGA, new String(yytext()));
          }
        case 58: break;
        case 24: 
          { System.out.print(" recto ");
                          return symbol(sym.RECTO, new String(yytext()));
          }
        case 59: break;
        case 25: 
          { System.out.print("false");
                          return symbol(sym.FALSE);
          }
        case 60: break;
        case 26: 
          { System.out.print(" medio ");
                          return symbol(sym.MEDIO, new String(yytext()));
          }
        case 61: break;
        case 27: 
          { System.out.print(" mover ");
                          return symbol(sym.MOVER, new String(yytext()));
          }
        case 62: break;
        case 28: 
          { System.out.print(" anular ");
                          return symbol(sym.ANULAR, new String(yytext()));
          }
        case 63: break;
        case 29: 
          { System.out.print(" índice ");
                          return symbol(sym.INDICE, new String(yytext()));
          }
        case 64: break;
        case 30: 
          { System.out.print(" pulgar ");
                          return symbol(sym.PULGAR, new String(yytext()));
          }
        case 65: break;
        case 31: 
          { System.out.print(" meñique ");
                          return symbol(sym.MENIQUE, new String(yytext()));
          }
        case 66: break;
        case 32: 
          { System.out.print(" entonces ");
                          return symbol(sym.ENTONCES, new String(yytext()));
          }
        case 67: break;
        case 33: 
          { System.out.print(" circular ");
                          return symbol(sym.CIRCULAR, new String(yytext()));
          }
        case 68: break;
        case 34: 
          { System.out.print(" mientras ");
                          return symbol(sym.MIENTRAS, new String(yytext()));
          }
        case 69: break;
        case 35: 
          { System.out.print("declarar ");
                          return symbol(sym.DECLARAR, new String(yytext()));
          }
        case 70: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
