
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jun 20 22:49:27 CST 2014
//----------------------------------------------------

package gramatica;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAVDER = 8;
  public static final int PULGAR = 31;
  public static final int MENIQUE = 27;
  public static final int IGUAL = 22;
  public static final int MAYIGUAL = 21;
  public static final int ENTONCES = 16;
  public static final int TRUE = 11;
  public static final int DECLARAR = 24;
  public static final int ID = 10;
  public static final int OP_SUMA = 2;
  public static final int NUM = 33;
  public static final int HAGA = 15;
  public static final int ANULAR = 28;
  public static final int MENIGUAL = 20;
  public static final int MEDIO = 29;
  public static final int DISTINTO = 23;
  public static final int EOF = 0;
  public static final int MOVER = 32;
  public static final int CIRCULAR = 26;
  public static final int SINO = 14;
  public static final int OP_DIV = 5;
  public static final int SI = 13;
  public static final int PARENIZQ = 6;
  public static final int FALSE = 12;
  public static final int error = 1;
  public static final int INDICE = 30;
  public static final int MENQUE = 18;
  public static final int PARENDER = 7;
  public static final int OP_MULT = 4;
  public static final int RECTO = 25;
  public static final int OP_RESTA = 3;
  public static final int MIENTRAS = 17;
  public static final int MAYQUE = 19;
  public static final int LLAVIZQ = 9;
}

